### ISSUE TITLE
allow to set different type in column name

### ISSUE THREAD

**Issue by edgurgel** [jsevellec/cassandra-unit#40]
I would like to describe a DefaultComparatorType. So we could have something like this:

``` yaml
- name: columnFamily
  type: STANDARD
  keyType: CompositeType(UUIDType,LongType)
  defaultColumnValueType: LongType
  defaultComparatorType: LongType
  rows:
  - key: 371dd0e3-3bc6-4a88-9eeb-37f9a8eccf6b:101
    columns:
    - {name: 1, value: 3}
    - {name: float(1.5), value: 1029}
   - {name: 20, value: 23}
```

The default column name is Long, but it would be possible to describe other column names.

Am I asking something stupid? Or using the wrong definitions?
